### PR TITLE
Feature support for HTML copy & pasting

### PR DESCRIPTION
**Pull request by parasharrajat**
# Overview

Add support for HTML copy-pasting.
* Most of the app supports direct HTML copy-pasting and now Android and IOS also support native HTML MIME type in their respective clipboard APIs. 
For example, 
In our app, we use markdown for formatting. we support a feature that allows copying existing messages and Users should be able to see the Markup when pasted into our or other apps. (eg. Google docs).

### Platfrom
- [x] Android
- [x] IOS
- [ ] Web

# Test Plan

* I have updated the existing example repo to cover the HTML copy functionality and tested it there as well.
* Added mocks.
* :question: Example repo does have web extension.

### CODE REVIEW

**Comment by parasharrajat** [comment]
I am planning to add web implementation but I see that react-native-web has a better implementation than our current `setString method` can I modify that as well. So that it does not affect the API but get improved.

**Comment by lorenjohnson** [comment]
Hi! Will this still happen at some point? Been scanning the scene for a good way to copy/past HTML in our app and not finding much that fits except an expo library which won't work for us because we're not wanting to add the whole relate Expo dependency tree...

**Comment by parasharrajat** [comment]
I closed the PR as this change was no more needed for our use case. But I think the code is still valid. Only the web implementation is missing which I never got the chance to work on. 

Feel free to use it.

**Comment by lorenjohnson** [comment]
Thanks for the reply! That's good news, we don't need web. However I'm reticent to dependency to a branch... Maybe if I find some "spare time" I can extend it to Web and submit a PR :)

**Pull request closed without merging**
