### PR TITLE
Add new architecture support - convert library to turbomodule

### PR DESCRIPTION
**Pull request by j-piasecki**
# Overview
This PR:
- adds a new `FabricExample` app dedicated to testing the new architecture
- updates the commented out spec to include the added methods
- includes interoperability between the old and the new architecture

# Test Plan
Use the added `FabricExample` app to test the turbomodule which has the new architecture enabled.

### CODE REVIEW

**Review by Naturalclar — APPROVED** [review]
Thank you!

**Comment by WoLewicki** [comment]
@Naturalclar could we get this released so people can test if all works correctly?

**Comment by Naturalclar** [comment]
@WoLewicki sorry for the delay, just released 1.13.0 with the changes!

**Comment by gabrieldonadel** [comment]
why did this remove compatibility with macOS from `RNCClipboard.podspec`?

**Comment by j-piasecki** [comment]
> why did this remove compatibility with macOS from RNCClipboard.podspec?

I must've missed it, thanks for the quick fix though!

**Pull request merged**
