### PR TITLE
Web support

### PR DESCRIPTION
**Pull request by BrendonSled**
# Overview
This PR adds web support to clipboard.

Closes issue #5

### CODE REVIEW

**Comment by BrendonSled** [comment]
Can I get a review on this or some feedback? @Naturalclar

**Comment by chakrihacker** [comment]
Hey @BrendonSled can you update tsconfig file, lib array with dom, in order to fix failing test cases

**Comment by chakrihacker** [comment]
tests are failing

**Comment by chakrihacker** [comment]
`yarn run build` shouldn't throw any error on your local machine

**Comment by BrendonSled** [comment]
Ah thanks, so there's some issues with the typings. `@types/react-native` includes a subset of the dom typings. Typescript is throwing an error because there is duplicate types. 

There's two ways we can solve this. 
1) Add `"skipLibCheck": true,` to the tsconfig
2) Create our own navigator type definition for the subset we need. (this is directly from the ts dom library)

```
declare var navigator: {
  clipboard: {
    readText(): Promise<string>;
    writeText(data: string): Promise<void>;
  };
};
```

Thoughts?

**Review by Naturalclar — APPROVED** [review]
@BrendonSled sorry for the long delay! I'll merge this PR and make a release soon.
Thanks for this change!

**Review by Naturalclar — APPROVED** [review]

**Comment by MohammadAzimi** [comment]
That's cool @BrendonSled😍But do all the browsers support navigator?

**Comment by BrendonSled** [comment]
> That's cool @BrendonSled😍But do all the browsers support navigator?

https://caniuse.com/async-clipboard

Here are the supported browsers

**Comment by MohammadAzimi** [comment]
> > That's cool @BrendonSled😍But do all the browsers support navigator?
> 
> https://caniuse.com/async-clipboard
> 
> Here are the supported browsers

I see and still some of the browsers like **ios safari** don't support clipboard API well.
As a suggestion isn't it better to implement `getString` and `setString` functions in other ways? (a bit dirty but with wider support)

for example `setString` like this 
```js
const setString = (content: string) => {
   const el = document.createElement('textarea');
   el.value = content;
   document.body.appendChild(el);
   el.select();
   document.execCommand('copy');
   document.body.removeChild(el);
};
```

**Comment by BrendonSled** [comment]
Thanks @MohammadAzimi I'll create a PR for back support

**Pull request merged**
