### PR TITLE
feat: getImage iOS

### PR DESCRIPTION
**Pull request by s77rt**
# Overview
Added `getImage` support for iOS. 

# Test Plan
1. Copy JPEG image
2. Paste the image and verify it's pasted as jpeg
3. Copy PNG image
4. Paste the image and verify it's pasted as png
5. Copy GIF image
6. Paste the image and verify it's pasted as gif

https://github.com/user-attachments/assets/2231b890-8698-49bf-be40-461d79607fc7

https://github.com/user-attachments/assets/699eea6f-3b97-4df8-be25-ab54d0821d6a

### CODE REVIEW

**Comment by s77rt** [comment]
In our use case, we need to use `getImage` because using `getImagePNG` for JPEG is slower

| Copying as JPEG | Copying as PNG |
|:---------------:|:--------------:|
|    <video src="https://github.com/user-attachments/assets/64635911-87da-4c79-90e1-fa27eccee634" />             |    <video src="https://github.com/user-attachments/assets/35ceb118-6497-43a2-8865-d06f4970de06" />            |

**Comment by s77rt** [comment]
Putting this on draft while I add more support to more types including GIF

**Comment by s77rt** [comment]
Ready for review

**Comment by durdevic** [comment]
Amazing! How did you enable text input to capture the Paste event?

**Review by durdevic — APPROVED** [review]
Seems to be good 👍

**Comment by durdevic** [comment]
Perfect, thanks for that one! @s77rt 

Let's hope both got merged in the next release 🤞

**Review by Naturalclar — APPROVED** [review]
thank you so much! lgtm

**Pull request merged**
